server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ws_pay_products
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: cbgomes
    password: cbgomes
  application:
    name: pay_product

ws:
  product:
    rabbitmq:
      exchange: ws-products
      queue: ws.products.queue

security:
  jwt:
    token:
      secret-key: chave-microservice
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka
